import os

output = []
output.append("# THIS IS AN AUTOMATICALLY GENERATED FILE. DO NOT MODIFY\n")
output.append("# THIS FILE IS GENERATED BY 'scripts/combine.py'\n\n")


files = ['shims', 'utils', 'mapping', 'mutablemapping', 'chainmap', 'template']

for fname in files:
    with open(f"../template/{fname}.py", "r", encoding='utf-8') as f:
        output.append(f"""# ================ {fname}.py ================\n""")
        for line in f.readlines():
            if not(line.startswith("import .") or line.startswith("from .")):
                output.append(line)
        output.append("\n\n")

with open("../combined_output/combined.mpy", "w", encoding='utf-8') as f:
    f.write("".join(output))
    